name: Deploy to EKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region ap-south-1 --name devops-eks-cluster

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/flask-deployment flask-app=<your-ecr-url>:latest
